# Generated by Django 4.2.7 on 2026-01-07 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_district_customuser_open_address_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atama Tarihi')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('SCHEDULED', 'Teslimat Atandı'), ('OUT_FOR_DELIVERY', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal')], default='PLANNED', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Ürün Atama',
                'verbose_name_plural': 'Ürün Atamaları',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['delivery_order', 'scheduled_date'], 'verbose_name': 'Teslimat', 'verbose_name_plural': 'Teslimatlar'},
        ),
        migrations.AlterModelOptions(
            name='deliveryroute',
            options={'verbose_name': 'Teslimat Rotası', 'verbose_name_plural': 'Teslimat Rotaları'},
        ),
        migrations.AlterModelOptions(
            name='deliveryroutestop',
            options={'ordering': ['stop_order'], 'verbose_name': 'Teslimat Durağı', 'verbose_name_plural': 'Teslimat Durakları'},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryroutestop',
            unique_together={('route', 'stop_order')},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='product_ownership',
        ),
        migrations.AddField(
            model_name='customuser',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Geocode Tarihi'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='address_snapshot',
            field=models.TextField(blank=True, null=True, verbose_name='Adres (Snapshot)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_phone_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Müşteri Tel (Snapshot)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Teslim Eden Personel'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Teslimat Sırası'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Mesafe (KM)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='eta_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tahmini Süre (dk)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='route_batch_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rota Batch ID'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planlanan Tarih'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='time_window_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Zaman Aralığı Bitiş'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='time_window_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Zaman Aralığı Başlangıç'),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='route_polyline',
            field=models.TextField(blank=True, null=True, verbose_name='Rota Polyline'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Teslimat Adresi'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Bekliyor'), ('OUT_FOR_DELIVERY', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('FAILED', 'Başarısız')], default='WAITING', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='deliveryroute',
            name='optimized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Optimizasyon Tarihi'),
        ),
        migrations.AlterField(
            model_name='deliveryroutestop',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_stop', to='products.delivery', verbose_name='Teslimat'),
        ),
        migrations.AlterField(
            model_name='deliveryroutestop',
            name='distance_from_previous_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Önceki Noktadan Mesafe (km)'),
        ),
        migrations.AlterField(
            model_name='deliveryroutestop',
            name='duration_from_previous_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Önceki Noktadan Süre (dk)'),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE products_deliveryroutestop ALTER COLUMN estimated_arrival TYPE timestamp with time zone USING CURRENT_DATE + estimated_arrival;',
            reverse_sql='ALTER TABLE products_deliveryroutestop ALTER COLUMN estimated_arrival TYPE time without time zone USING estimated_arrival::time;',
            state_operations=[
                migrations.AlterField(
                    model_name='deliveryroutestop',
                    name='estimated_arrival',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Tahmini Varış'),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='deliveryroutestop',
            name='stop_order',
            field=models.PositiveIntegerField(verbose_name='Sıra No'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['scheduled_date'], name='products_de_schedul_e1ea6c_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='products_de_status_3d4e86_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['route_batch_id'], name='products_de_route_b_a1950f_idx'),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Atayan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='productassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='products.product', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='products.productassignment', verbose_name='Satış Kaydı'),
        ),
    ]
