# Generated by Django 4.2.7 on 2026-01-21 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassignment',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Satış Yapıldı'), ('SCHEDULED', 'Teslimat Planlandı'), ('OUT_FOR_DELIVERY', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal')], default='PLANNED', max_length=20, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_service_updates', models.BooleanField(default=True, verbose_name='Servis Güncellemeleri')),
                ('notify_price_drops', models.BooleanField(default=True, verbose_name='Fiyat Düşüşleri')),
                ('notify_restock', models.BooleanField(default=True, verbose_name='Stok Bildirimleri')),
                ('notify_recommendations', models.BooleanField(default=True, verbose_name='Ürün Önerileri')),
                ('notify_warranty_expiry', models.BooleanField(default=True, verbose_name='Garanti Süresi Uyarıları')),
                ('notify_general', models.BooleanField(default=True, verbose_name='Genel Bildirimler')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim Tercihi',
                'verbose_name_plural': 'Bildirim Tercihleri',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_address', models.TextField(blank=True, help_text='Ev/Apartman numarası, cadde, sokak vb.', null=True, verbose_name='Açık Adres')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir (Legacy)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude koordinatı', max_digits=10, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude koordinatı', max_digits=10, null=True, verbose_name='Boylam')),
                ('geocoded_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Geocode Tarihi')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_addresses', to='products.area', verbose_name='Mahalle/Köy')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_addresses', to='products.district', verbose_name='İlçe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Müşteri Adresi',
                'verbose_name_plural': 'Müşteri Adresleri',
            },
        ),
    ]
