# Generated by Django 4.2.7 on 2026-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_migrate_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_lng',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='area',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='geocoded_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notify_general',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notify_price_drops',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notify_recommendations',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notify_restock',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notify_service_updates',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notify_warranty_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='open_address',
        ),
    ]
