# Generated by Django 4.2.7 on 2026-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Satıcı'), ('customer', 'Müşteri'), ('delivery', 'Teslimat Personeli')], default='customer', max_length=10),
        ),
    ]
