# Generated by Django 4.2.7 on 2026-03-07 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'delivery_person'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL, verbose_name='Teslimatçı'),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planlandı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı')], default='PLANNED', max_length=20, verbose_name='Rota Durumu'),
        ),
        migrations.AlterField(
            model_name='deliveryroute',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
    ]
