# Generated by Django 4.2.7 on 2026-03-07 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_add_route_driver_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryroute',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'delivery'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL, verbose_name='Teslimatçı'),
        ),
    ]
