# Generated by Django 4.2.7 on 2026-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_fix_delivery_role_limit_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='campaign_tag',
            field=models.TextField(blank=True, null=True, verbose_name='Kampanya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/'),
        ),
    ]
