# Generated by Django 4.2.7 on 2026-03-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_campaign_tag_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='biometric_device_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.JSONField(blank=True, help_text="Mathematical representation of the user's face (extracted via DeepFace)", null=True, verbose_name='Yüz Özellik Vektörü'),
        ),
    ]
