# Generated by Django 4.2.7 on 2026-03-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_campaign_tag_alter_product_image'),
        ('products', '0022_alter_servicequeue_priority'),
    ]

    operations = [
    ]
