# Generated by Django 4.2.7 on 2026-03-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_customuser_biometric_device_id_and_more'),
        ('products', '0024_service_request_assignment_support'),
    ]

    operations = [
    ]
