# Generated by Django 4.2.7 on 2026-03-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_merge_20260322_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: ncf_model.pkl, content_model.pkl', max_length=100, unique=True, verbose_name='Model Dosya Adı')),
                ('data', models.BinaryField(verbose_name='Model Verisi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'ML Model Deposu',
                'verbose_name_plural': 'ML Model Depoları',
            },
        ),
    ]
