# Generated by Django 4.2.7 on 2026-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_mlmodelstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='dismissed',
            field=models.BooleanField(default=False, help_text='Kullanıcı bu öneriyi reddetmiş'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
